---
apiVersion: v1
kind: Service
metadata:
  name: "fortune-system"
  labels:
    app: "fortune-api"
    tier: "frontend"
  annotations:
    serviceloadbalancer/lb.host: "fortune.shinton.net"
spec:
  type: "ClusterIP"
  selector:
    app: "fortune-api"
    tier: "frontend"
  ports:
    - port: 80
      targetPort: 80